server:
  port: 8082
  
spring:
  datasource:
    url: jdbc:h2:mem:VaccinationCenterDB
    driver-class-name:  org.h2.Driver
    username: sa
    password: sa
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true 
  application:
    name: VACCINATION-CENTER-SERVICE